# Generated by Django 4.1.6 on 2023-03-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_task',
            name='date',
            field=models.DateField(default='2000-01-23'),
            preserve_default=False,
        ),
    ]
